### ISSUE TITLE
План до 6 марта

### ISSUE THREAD

**Issue by LiubovAnt** [Lamblador/IR_expert_system#3]
- [x] Изучить RDKit, понять как эмбедить формулы.
- [x] Разобраться с шагом x. Привести к масштабу.
- [x] Разобраться с необходимостью нормировки по y.
- [x] Выбрать классы.
- [x] * Начать разметку, изучить статистику по датасету, какие классы есть, в каком колличестве.

**Comment by Lamblador** [comment]
Перенесён на будущее.
Изучить RDKit, понять как эмбедить формулы.
